packages:
  - .
allowBuilds:
  '@prisma/engines': false
  esbuild: false
  msgpackr-extract: set this to true or false
  prisma: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
